# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sci_tool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 559)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("instaspin.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.maintabwidget = QtWidgets.QTabWidget(self.centralwidget)
        self.maintabwidget.setObjectName("maintabwidget")
        self.scitooltab = QtWidgets.QWidget()
        self.scitooltab.setObjectName("scitooltab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scitooltab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.distext = QtWidgets.QTabWidget(self.scitooltab)
        self.distext.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distext.sizePolicy().hasHeightForWidth())
        self.distext.setSizePolicy(sizePolicy)
        self.distext.setMaximumSize(QtCore.QSize(194, 16777215))
        self.distext.setTabPosition(QtWidgets.QTabWidget.North)
        self.distext.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.distext.setUsesScrollButtons(True)
        self.distext.setTabsClosable(False)
        self.distext.setMovable(False)
        self.distext.setObjectName("distext")
        self.dishextext = QtWidgets.QWidget()
        self.dishextext.setMouseTracking(False)
        self.dishextext.setObjectName("dishextext")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dishextext)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dishex = QtWidgets.QPlainTextEdit(self.dishextext)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.dishex.setFont(font)
        self.dishex.setReadOnly(True)
        self.dishex.setObjectName("dishex")
        self.verticalLayout_7.addWidget(self.dishex)
        self.distext.addTab(self.dishextext, "")
        self.disstringtext = QtWidgets.QWidget()
        self.disstringtext.setObjectName("disstringtext")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.disstringtext)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.distring = QtWidgets.QPlainTextEdit(self.disstringtext)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.distring.setFont(font)
        self.distring.setReadOnly(True)
        self.distring.setObjectName("distring")
        self.verticalLayout_10.addWidget(self.distring)
        self.distext.addTab(self.disstringtext, "")
        self.Protocoltab = QtWidgets.QWidget()
        self.Protocoltab.setEnabled(False)
        self.Protocoltab.setObjectName("Protocoltab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Protocoltab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.Protocoltab)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(self.Protocoltab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.framehead_edit = QtWidgets.QLineEdit(self.Protocoltab)
        self.framehead_edit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.framehead_edit.setMaxLength(2)
        self.framehead_edit.setCursorPosition(2)
        self.framehead_edit.setObjectName("framehead_edit")
        self.horizontalLayout_2.addWidget(self.framehead_edit)
        self.label_2 = QtWidgets.QLabel(self.Protocoltab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.framenum_edit = QtWidgets.QLineEdit(self.Protocoltab)
        self.framenum_edit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.framenum_edit.setObjectName("framenum_edit")
        self.horizontalLayout_2.addWidget(self.framenum_edit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.framesumcheck = QtWidgets.QCheckBox(self.Protocoltab)
        self.framesumcheck.setChecked(True)
        self.framesumcheck.setObjectName("framesumcheck")
        self.horizontalLayout_8.addWidget(self.framesumcheck)
        self.label_3 = QtWidgets.QLabel(self.Protocoltab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.framend_edit = QtWidgets.QLineEdit(self.Protocoltab)
        self.framend_edit.setObjectName("framend_edit")
        self.horizontalLayout_8.addWidget(self.framend_edit)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.disprotocol = QtWidgets.QPlainTextEdit(self.Protocoltab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.disprotocol.setFont(font)
        self.disprotocol.setReadOnly(True)
        self.disprotocol.setObjectName("disprotocol")
        self.verticalLayout_5.addWidget(self.disprotocol)
        self.distext.addTab(self.Protocoltab, "")
        self.verticalLayout_3.addWidget(self.distext)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.clrcontentbutton = QtWidgets.QPushButton(self.scitooltab)
        self.clrcontentbutton.setObjectName("clrcontentbutton")
        self.horizontalLayout_16.addWidget(self.clrcontentbutton)
        self.savecontentbutton = QtWidgets.QPushButton(self.scitooltab)
        self.savecontentbutton.setObjectName("savecontentbutton")
        self.horizontalLayout_16.addWidget(self.savecontentbutton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.line_6 = QtWidgets.QFrame(self.scitooltab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.portlabel = QtWidgets.QLabel(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portlabel.sizePolicy().hasHeightForWidth())
        self.portlabel.setSizePolicy(sizePolicy)
        self.portlabel.setMinimumSize(QtCore.QSize(60, 0))
        self.portlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.portlabel.setFont(font)
        self.portlabel.setObjectName("portlabel")
        self.horizontalLayout_4.addWidget(self.portlabel)
        spacerItem = QtWidgets.QSpacerItem(10, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.scitooltab)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.portcomtext = QtWidgets.QLineEdit(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portcomtext.sizePolicy().hasHeightForWidth())
        self.portcomtext.setSizePolicy(sizePolicy)
        self.portcomtext.setMinimumSize(QtCore.QSize(35, 25))
        self.portcomtext.setMaximumSize(QtCore.QSize(40, 16777215))
        self.portcomtext.setMaxLength(2)
        self.portcomtext.setFrame(True)
        self.portcomtext.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.portcomtext.setAlignment(QtCore.Qt.AlignCenter)
        self.portcomtext.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.portcomtext.setObjectName("portcomtext")
        self.horizontalLayout_4.addWidget(self.portcomtext)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bandratelabel = QtWidgets.QLabel(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandratelabel.sizePolicy().hasHeightForWidth())
        self.bandratelabel.setSizePolicy(sizePolicy)
        self.bandratelabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bandratelabel.setFont(font)
        self.bandratelabel.setObjectName("bandratelabel")
        self.horizontalLayout_3.addWidget(self.bandratelabel)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.baudratecombo = QtWidgets.QComboBox(self.scitooltab)
        self.baudratecombo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudratecombo.sizePolicy().hasHeightForWidth())
        self.baudratecombo.setSizePolicy(sizePolicy)
        self.baudratecombo.setMinimumSize(QtCore.QSize(0, 25))
        self.baudratecombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.baudratecombo.setBaseSize(QtCore.QSize(0, 0))
        self.baudratecombo.setEditable(False)
        self.baudratecombo.setObjectName("baudratecombo")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.baudratecombo.addItem("")
        self.horizontalLayout_3.addWidget(self.baudratecombo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.databitlabel = QtWidgets.QLabel(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitlabel.sizePolicy().hasHeightForWidth())
        self.databitlabel.setSizePolicy(sizePolicy)
        self.databitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.databitlabel.setFont(font)
        self.databitlabel.setObjectName("databitlabel")
        self.horizontalLayout_5.addWidget(self.databitlabel)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.databitcombo = QtWidgets.QComboBox(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitcombo.sizePolicy().hasHeightForWidth())
        self.databitcombo.setSizePolicy(sizePolicy)
        self.databitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.databitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.databitcombo.setObjectName("databitcombo")
        self.databitcombo.addItem("")
        self.databitcombo.addItem("")
        self.databitcombo.addItem("")
        self.databitcombo.addItem("")
        self.horizontalLayout_5.addWidget(self.databitcombo)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkbitlabel = QtWidgets.QLabel(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitlabel.sizePolicy().hasHeightForWidth())
        self.checkbitlabel.setSizePolicy(sizePolicy)
        self.checkbitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkbitlabel.setFont(font)
        self.checkbitlabel.setObjectName("checkbitlabel")
        self.horizontalLayout_6.addWidget(self.checkbitlabel)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.checkbitcombo = QtWidgets.QComboBox(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitcombo.sizePolicy().hasHeightForWidth())
        self.checkbitcombo.setSizePolicy(sizePolicy)
        self.checkbitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.checkbitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.checkbitcombo.setObjectName("checkbitcombo")
        self.checkbitcombo.addItem("")
        self.checkbitcombo.addItem("")
        self.checkbitcombo.addItem("")
        self.checkbitcombo.addItem("")
        self.checkbitcombo.addItem("")
        self.horizontalLayout_6.addWidget(self.checkbitcombo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stopbitlabel = QtWidgets.QLabel(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitlabel.sizePolicy().hasHeightForWidth())
        self.stopbitlabel.setSizePolicy(sizePolicy)
        self.stopbitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopbitlabel.setFont(font)
        self.stopbitlabel.setObjectName("stopbitlabel")
        self.horizontalLayout_7.addWidget(self.stopbitlabel)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.stopbitcombo = QtWidgets.QComboBox(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitcombo.sizePolicy().hasHeightForWidth())
        self.stopbitcombo.setSizePolicy(sizePolicy)
        self.stopbitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.stopbitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.stopbitcombo.setObjectName("stopbitcombo")
        self.stopbitcombo.addItem("")
        self.stopbitcombo.addItem("")
        self.stopbitcombo.addItem("")
        self.horizontalLayout_7.addWidget(self.stopbitcombo)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.sciopenButton = QtWidgets.QPushButton(self.scitooltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sciopenButton.sizePolicy().hasHeightForWidth())
        self.sciopenButton.setSizePolicy(sizePolicy)
        self.sciopenButton.setMaximumSize(QtCore.QSize(194, 16777215))
        self.sciopenButton.setCheckable(True)
        self.sciopenButton.setChecked(False)
        self.sciopenButton.setObjectName("sciopenButton")
        self.verticalLayout.addWidget(self.sciopenButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.debugtab = QtWidgets.QTabWidget(self.scitooltab)
        self.debugtab.setEnabled(True)
        self.debugtab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.debugtab.setObjectName("debugtab")
        self.sendtab = QtWidgets.QWidget()
        self.sendtab.setObjectName("sendtab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sendtab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sendclr_Button = QtWidgets.QPushButton(self.sendtab)
        self.sendclr_Button.setObjectName("sendclr_Button")
        self.horizontalLayout_9.addWidget(self.sendclr_Button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label_10 = QtWidgets.QLabel(self.sendtab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.char_radioButton = QtWidgets.QRadioButton(self.sendtab)
        self.char_radioButton.setObjectName("char_radioButton")
        self.horizontalLayout_9.addWidget(self.char_radioButton)
        self.hex_radioButton = QtWidgets.QRadioButton(self.sendtab)
        self.hex_radioButton.setAcceptDrops(False)
        self.hex_radioButton.setChecked(True)
        self.hex_radioButton.setObjectName("hex_radioButton")
        self.horizontalLayout_9.addWidget(self.hex_radioButton)
        self.mainsend_Button = QtWidgets.QPushButton(self.sendtab)
        self.mainsend_Button.setObjectName("mainsend_Button")
        self.horizontalLayout_9.addWidget(self.mainsend_Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.mainsend_Edit = QtWidgets.QTextEdit(self.sendtab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.mainsend_Edit.setFont(font)
        self.mainsend_Edit.setObjectName("mainsend_Edit")
        self.verticalLayout_8.addWidget(self.mainsend_Edit)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line_2 = QtWidgets.QFrame(self.sendtab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.sendtab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.cmd1_Edit = QtWidgets.QLineEdit(self.sendtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd1_Edit.sizePolicy().hasHeightForWidth())
        self.cmd1_Edit.setSizePolicy(sizePolicy)
        self.cmd1_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.cmd1_Edit.setFont(font)
        self.cmd1_Edit.setObjectName("cmd1_Edit")
        self.horizontalLayout_11.addWidget(self.cmd1_Edit)
        self.cmd1sned_Button = QtWidgets.QPushButton(self.sendtab)
        self.cmd1sned_Button.setObjectName("cmd1sned_Button")
        self.horizontalLayout_11.addWidget(self.cmd1sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.line = QtWidgets.QFrame(self.sendtab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.sendtab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.cmd2_Edit = QtWidgets.QLineEdit(self.sendtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd2_Edit.sizePolicy().hasHeightForWidth())
        self.cmd2_Edit.setSizePolicy(sizePolicy)
        self.cmd2_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.cmd2_Edit.setFont(font)
        self.cmd2_Edit.setObjectName("cmd2_Edit")
        self.horizontalLayout_12.addWidget(self.cmd2_Edit)
        self.cmd2sned_Button = QtWidgets.QPushButton(self.sendtab)
        self.cmd2sned_Button.setObjectName("cmd2sned_Button")
        self.horizontalLayout_12.addWidget(self.cmd2sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.line_3 = QtWidgets.QFrame(self.sendtab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.sendtab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.cmd3_Edit = QtWidgets.QLineEdit(self.sendtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd3_Edit.sizePolicy().hasHeightForWidth())
        self.cmd3_Edit.setSizePolicy(sizePolicy)
        self.cmd3_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.cmd3_Edit.setFont(font)
        self.cmd3_Edit.setObjectName("cmd3_Edit")
        self.horizontalLayout_13.addWidget(self.cmd3_Edit)
        self.cmd3sned_Button = QtWidgets.QPushButton(self.sendtab)
        self.cmd3sned_Button.setObjectName("cmd3sned_Button")
        self.horizontalLayout_13.addWidget(self.cmd3sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.line_4 = QtWidgets.QFrame(self.sendtab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.sendtab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.cmd4_Edit = QtWidgets.QLineEdit(self.sendtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd4_Edit.sizePolicy().hasHeightForWidth())
        self.cmd4_Edit.setSizePolicy(sizePolicy)
        self.cmd4_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cmd4_Edit.setFont(font)
        self.cmd4_Edit.setObjectName("cmd4_Edit")
        self.horizontalLayout_14.addWidget(self.cmd4_Edit)
        self.cmd4sned_Button = QtWidgets.QPushButton(self.sendtab)
        self.cmd4sned_Button.setObjectName("cmd4sned_Button")
        self.horizontalLayout_14.addWidget(self.cmd4sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.line_5 = QtWidgets.QFrame(self.sendtab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_9.addWidget(self.line_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.sendtab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.cmd5_Edit = QtWidgets.QLineEdit(self.sendtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd5_Edit.sizePolicy().hasHeightForWidth())
        self.cmd5_Edit.setSizePolicy(sizePolicy)
        self.cmd5_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.cmd5_Edit.setFont(font)
        self.cmd5_Edit.setObjectName("cmd5_Edit")
        self.horizontalLayout_15.addWidget(self.cmd5_Edit)
        self.cmd5sned_Button = QtWidgets.QPushButton(self.sendtab)
        self.cmd5sned_Button.setObjectName("cmd5sned_Button")
        self.horizontalLayout_15.addWidget(self.cmd5sned_Button)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_9.setStretch(5, 1)
        self.verticalLayout_9.setStretch(7, 1)
        self.verticalLayout_9.setStretch(9, 1)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 1)
        self.debugtab.addTab(self.sendtab, "")
        self.debugdatatab = QtWidgets.QWidget()
        self.debugdatatab.setObjectName("debugdatatab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.debugdatatab)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.x1_checkBox = QtWidgets.QCheckBox(self.debugdatatab)
        self.x1_checkBox.setObjectName("x1_checkBox")
        self.horizontalLayout_20.addWidget(self.x1_checkBox)
        self.x1_low_line = QtWidgets.QLineEdit(self.debugdatatab)
        self.x1_low_line.setInputMask("")
        self.x1_low_line.setMaxLength(6)
        self.x1_low_line.setObjectName("x1_low_line")
        self.horizontalLayout_20.addWidget(self.x1_low_line)
        self.label_12 = QtWidgets.QLabel(self.debugdatatab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_20.addWidget(self.label_12)
        self.x1_high_line = QtWidgets.QLineEdit(self.debugdatatab)
        self.x1_high_line.setInputMask("")
        self.x1_high_line.setMaxLength(6)
        self.x1_high_line.setObjectName("x1_high_line")
        self.horizontalLayout_20.addWidget(self.x1_high_line)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.x1_plainTextEdit = QtWidgets.QPlainTextEdit(self.debugdatatab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.x1_plainTextEdit.setFont(font)
        self.x1_plainTextEdit.setReadOnly(True)
        self.x1_plainTextEdit.setObjectName("x1_plainTextEdit")
        self.verticalLayout_13.addWidget(self.x1_plainTextEdit)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.x1clr_button = QtWidgets.QPushButton(self.debugdatatab)
        self.x1clr_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x1clr_button.setObjectName("x1clr_button")
        self.horizontalLayout_23.addWidget(self.x1clr_button)
        self.x1save_button = QtWidgets.QPushButton(self.debugdatatab)
        self.x1save_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x1save_button.setObjectName("x1save_button")
        self.horizontalLayout_23.addWidget(self.x1save_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.x2_checkBox = QtWidgets.QCheckBox(self.debugdatatab)
        self.x2_checkBox.setObjectName("x2_checkBox")
        self.horizontalLayout_21.addWidget(self.x2_checkBox)
        self.x2_low_line = QtWidgets.QLineEdit(self.debugdatatab)
        self.x2_low_line.setInputMask("")
        self.x2_low_line.setMaxLength(6)
        self.x2_low_line.setObjectName("x2_low_line")
        self.horizontalLayout_21.addWidget(self.x2_low_line)
        self.label_13 = QtWidgets.QLabel(self.debugdatatab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_21.addWidget(self.label_13)
        self.x2_high_line = QtWidgets.QLineEdit(self.debugdatatab)
        self.x2_high_line.setInputMask("")
        self.x2_high_line.setMaxLength(6)
        self.x2_high_line.setObjectName("x2_high_line")
        self.horizontalLayout_21.addWidget(self.x2_high_line)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.x2_plainTextEdit = QtWidgets.QPlainTextEdit(self.debugdatatab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.x2_plainTextEdit.setFont(font)
        self.x2_plainTextEdit.setReadOnly(True)
        self.x2_plainTextEdit.setObjectName("x2_plainTextEdit")
        self.verticalLayout_14.addWidget(self.x2_plainTextEdit)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.x2clr_button = QtWidgets.QPushButton(self.debugdatatab)
        self.x2clr_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x2clr_button.setObjectName("x2clr_button")
        self.horizontalLayout_24.addWidget(self.x2clr_button)
        self.x2save_button = QtWidgets.QPushButton(self.debugdatatab)
        self.x2save_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x2save_button.setObjectName("x2save_button")
        self.horizontalLayout_24.addWidget(self.x2save_button)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_18.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.x3_checkBox = QtWidgets.QCheckBox(self.debugdatatab)
        self.x3_checkBox.setObjectName("x3_checkBox")
        self.horizontalLayout_22.addWidget(self.x3_checkBox)
        self.x3_low_line = QtWidgets.QLineEdit(self.debugdatatab)
        self.x3_low_line.setInputMask("")
        self.x3_low_line.setMaxLength(6)
        self.x3_low_line.setObjectName("x3_low_line")
        self.horizontalLayout_22.addWidget(self.x3_low_line)
        self.label_14 = QtWidgets.QLabel(self.debugdatatab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_22.addWidget(self.label_14)
        self.x3_high_line = QtWidgets.QLineEdit(self.debugdatatab)
        self.x3_high_line.setInputMask("")
        self.x3_high_line.setMaxLength(6)
        self.x3_high_line.setObjectName("x3_high_line")
        self.horizontalLayout_22.addWidget(self.x3_high_line)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.x3_plainTextEdit = QtWidgets.QPlainTextEdit(self.debugdatatab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.x3_plainTextEdit.setFont(font)
        self.x3_plainTextEdit.setReadOnly(True)
        self.x3_plainTextEdit.setObjectName("x3_plainTextEdit")
        self.verticalLayout_15.addWidget(self.x3_plainTextEdit)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(2)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.x3clr_button = QtWidgets.QPushButton(self.debugdatatab)
        self.x3clr_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x3clr_button.setObjectName("x3clr_button")
        self.horizontalLayout_25.addWidget(self.x3clr_button)
        self.x3save_button = QtWidgets.QPushButton(self.debugdatatab)
        self.x3save_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x3save_button.setObjectName("x3save_button")
        self.horizontalLayout_25.addWidget(self.x3save_button)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.line_7 = QtWidgets.QFrame(self.debugdatatab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_12.addWidget(self.line_7)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.hexselec_radio = QtWidgets.QRadioButton(self.debugdatatab)
        self.hexselec_radio.setObjectName("hexselec_radio")
        self.horizontalLayout_19.addWidget(self.hexselec_radio)
        self.x1selec_radio = QtWidgets.QRadioButton(self.debugdatatab)
        self.x1selec_radio.setObjectName("x1selec_radio")
        self.horizontalLayout_19.addWidget(self.x1selec_radio)
        self.x2selec_radio = QtWidgets.QRadioButton(self.debugdatatab)
        self.x2selec_radio.setObjectName("x2selec_radio")
        self.horizontalLayout_19.addWidget(self.x2selec_radio)
        self.x3selec_radio = QtWidgets.QRadioButton(self.debugdatatab)
        self.x3selec_radio.setObjectName("x3selec_radio")
        self.horizontalLayout_19.addWidget(self.x3selec_radio)
        self.plotnum_Slider = QtWidgets.QSlider(self.debugdatatab)
        self.plotnum_Slider.setMinimum(50)
        self.plotnum_Slider.setMaximum(1000)
        self.plotnum_Slider.setProperty("value", 500)
        self.plotnum_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.plotnum_Slider.setObjectName("plotnum_Slider")
        self.horizontalLayout_19.addWidget(self.plotnum_Slider)
        self.plotnum_lineEdit = QtWidgets.QLineEdit(self.debugdatatab)
        self.plotnum_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.plotnum_lineEdit.setReadOnly(True)
        self.plotnum_lineEdit.setObjectName("plotnum_lineEdit")
        self.horizontalLayout_19.addWidget(self.plotnum_lineEdit)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 1)
        self.horizontalLayout_19.setStretch(2, 1)
        self.horizontalLayout_19.setStretch(3, 1)
        self.horizontalLayout_19.setStretch(4, 2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.debug_matplot_layout = QtWidgets.QHBoxLayout()
        self.debug_matplot_layout.setObjectName("debug_matplot_layout")
        self.verticalLayout_12.addLayout(self.debug_matplot_layout)
        self.verticalLayout_12.setStretch(0, 3)
        self.verticalLayout_12.setStretch(3, 4)
        self.debugtab.addTab(self.debugdatatab, "")
        self.matplottab = QtWidgets.QWidget()
        self.matplottab.setEnabled(False)
        self.matplottab.setObjectName("matplottab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.matplottab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Dataplot1 = QtWidgets.QHBoxLayout()
        self.Dataplot1.setSpacing(1)
        self.Dataplot1.setObjectName("Dataplot1")
        self.verticalLayout_6.addLayout(self.Dataplot1)
        self.Dataplot2 = QtWidgets.QHBoxLayout()
        self.Dataplot2.setSpacing(1)
        self.Dataplot2.setObjectName("Dataplot2")
        self.verticalLayout_6.addLayout(self.Dataplot2)
        self.Dataplot3 = QtWidgets.QHBoxLayout()
        self.Dataplot3.setSpacing(1)
        self.Dataplot3.setObjectName("Dataplot3")
        self.verticalLayout_6.addLayout(self.Dataplot3)
        self.debugtab.addTab(self.matplottab, "")
        self.Instaspintab = QtWidgets.QWidget()
        self.Instaspintab.setEnabled(False)
        self.Instaspintab.setObjectName("Instaspintab")
        self.debugtab.addTab(self.Instaspintab, "")
        self.horizontalLayout.addWidget(self.debugtab)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.maintabwidget.addTab(self.scitooltab, "")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.about_tab)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textBrowser = QtWidgets.QTextBrowser(self.about_tab)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_10.addWidget(self.textBrowser)
        self.maintabwidget.addTab(self.about_tab, "")
        self.verticalLayout_4.addWidget(self.maintabwidget)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.recnumlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.recnumlineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.recnumlineEdit.setReadOnly(True)
        self.recnumlineEdit.setObjectName("recnumlineEdit")
        self.horizontalLayout_17.addWidget(self.recnumlineEdit)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_17.addWidget(self.label_9)
        self.sendnum_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sendnum_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sendnum_lineEdit.setReadOnly(True)
        self.sendnum_lineEdit.setObjectName("sendnum_lineEdit")
        self.horizontalLayout_17.addWidget(self.sendnum_lineEdit)
        self.clrcntbutton = QtWidgets.QPushButton(self.centralwidget)
        self.clrcntbutton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.clrcntbutton.setObjectName("clrcntbutton")
        self.horizontalLayout_17.addWidget(self.clrcntbutton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.horizontalLayout_17.setStretch(2, 1)
        self.horizontalLayout_17.setStretch(3, 1)
        self.horizontalLayout_17.setStretch(4, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.maintabwidget.setCurrentIndex(0)
        self.distext.setCurrentIndex(0)
        self.baudratecombo.setCurrentIndex(16)
        self.debugtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DebugTool@nixianmin"))
        self.distext.setTabText(self.distext.indexOf(self.dishextext), _translate("MainWindow", "Hex"))
        self.distext.setTabText(self.distext.indexOf(self.disstringtext), _translate("MainWindow", "String"))
        self.checkBox.setText(_translate("MainWindow", "使能"))
        self.label.setText(_translate("MainWindow", "帧头："))
        self.framehead_edit.setInputMask(_translate("MainWindow", "HH; "))
        self.framehead_edit.setText(_translate("MainWindow", "FF"))
        self.label_2.setText(_translate("MainWindow", "数据："))
        self.framenum_edit.setInputMask(_translate("MainWindow", "99; "))
        self.framenum_edit.setText(_translate("MainWindow", "4"))
        self.framesumcheck.setText(_translate("MainWindow", "和校验"))
        self.label_3.setText(_translate("MainWindow", "帧尾："))
        self.framend_edit.setInputMask(_translate("MainWindow", "HH; "))
        self.framend_edit.setText(_translate("MainWindow", "FF"))
        self.distext.setTabText(self.distext.indexOf(self.Protocoltab), _translate("MainWindow", "Protocol"))
        self.clrcontentbutton.setText(_translate("MainWindow", "清除内容"))
        self.savecontentbutton.setText(_translate("MainWindow", "另存为"))
        self.portlabel.setText(_translate("MainWindow", "端口号："))
        self.lineEdit.setText(_translate("MainWindow", "Com Port"))
        self.portcomtext.setInputMask(_translate("MainWindow", "99; "))
        self.portcomtext.setText(_translate("MainWindow", "3"))
        self.bandratelabel.setText(_translate("MainWindow", "波特率："))
        self.baudratecombo.setItemText(0, _translate("MainWindow", "50"))
        self.baudratecombo.setItemText(1, _translate("MainWindow", "75"))
        self.baudratecombo.setItemText(2, _translate("MainWindow", "110"))
        self.baudratecombo.setItemText(3, _translate("MainWindow", "134"))
        self.baudratecombo.setItemText(4, _translate("MainWindow", "150"))
        self.baudratecombo.setItemText(5, _translate("MainWindow", "200"))
        self.baudratecombo.setItemText(6, _translate("MainWindow", "300"))
        self.baudratecombo.setItemText(7, _translate("MainWindow", "600"))
        self.baudratecombo.setItemText(8, _translate("MainWindow", "1200"))
        self.baudratecombo.setItemText(9, _translate("MainWindow", "1800"))
        self.baudratecombo.setItemText(10, _translate("MainWindow", "2400"))
        self.baudratecombo.setItemText(11, _translate("MainWindow", "4800"))
        self.baudratecombo.setItemText(12, _translate("MainWindow", "9600"))
        self.baudratecombo.setItemText(13, _translate("MainWindow", "19200"))
        self.baudratecombo.setItemText(14, _translate("MainWindow", "38400"))
        self.baudratecombo.setItemText(15, _translate("MainWindow", "57600"))
        self.baudratecombo.setItemText(16, _translate("MainWindow", "115200"))
        self.databitlabel.setText(_translate("MainWindow", "数据位："))
        self.databitcombo.setItemText(0, _translate("MainWindow", "8bit"))
        self.databitcombo.setItemText(1, _translate("MainWindow", "7bit"))
        self.databitcombo.setItemText(2, _translate("MainWindow", "6bit"))
        self.databitcombo.setItemText(3, _translate("MainWindow", "5bit"))
        self.checkbitlabel.setText(_translate("MainWindow", "校验位："))
        self.checkbitcombo.setItemText(0, _translate("MainWindow", "None无"))
        self.checkbitcombo.setItemText(1, _translate("MainWindow", "Even偶"))
        self.checkbitcombo.setItemText(2, _translate("MainWindow", "Odd奇"))
        self.checkbitcombo.setItemText(3, _translate("MainWindow", "Mark1"))
        self.checkbitcombo.setItemText(4, _translate("MainWindow", "Space0"))
        self.stopbitlabel.setText(_translate("MainWindow", "停止位："))
        self.stopbitcombo.setItemText(0, _translate("MainWindow", "1bit"))
        self.stopbitcombo.setItemText(1, _translate("MainWindow", "1.5bit"))
        self.stopbitcombo.setItemText(2, _translate("MainWindow", "2bit"))
        self.sciopenButton.setText(_translate("MainWindow", "打开"))
        self.sendclr_Button.setText(_translate("MainWindow", "清空数据"))
        self.label_10.setText(_translate("MainWindow", "数据格式:"))
        self.char_radioButton.setText(_translate("MainWindow", "Char"))
        self.hex_radioButton.setText(_translate("MainWindow", "Hex"))
        self.mainsend_Button.setText(_translate("MainWindow", "发送"))
        self.label_4.setText(_translate("MainWindow", "CMD1:"))
        self.cmd1sned_Button.setText(_translate("MainWindow", "发送"))
        self.label_5.setText(_translate("MainWindow", "CMD2:"))
        self.cmd2sned_Button.setText(_translate("MainWindow", "发送"))
        self.label_6.setText(_translate("MainWindow", "CMD3:"))
        self.cmd3sned_Button.setText(_translate("MainWindow", "发送"))
        self.label_7.setText(_translate("MainWindow", "CMD4:"))
        self.cmd4sned_Button.setText(_translate("MainWindow", "发送"))
        self.label_8.setText(_translate("MainWindow", "CMD5:"))
        self.cmd5sned_Button.setText(_translate("MainWindow", "发送"))
        self.debugtab.setTabText(self.debugtab.indexOf(self.sendtab), _translate("MainWindow", "SendData"))
        self.x1_checkBox.setText(_translate("MainWindow", "范围："))
        self.x1_low_line.setText(_translate("MainWindow", "-10"))
        self.label_12.setText(_translate("MainWindow", "< X1 <"))
        self.x1_high_line.setText(_translate("MainWindow", "10"))
        self.x1clr_button.setText(_translate("MainWindow", "清除数据"))
        self.x1save_button.setText(_translate("MainWindow", "另存为"))
        self.x2_checkBox.setText(_translate("MainWindow", "范围："))
        self.x2_low_line.setText(_translate("MainWindow", "10"))
        self.label_13.setText(_translate("MainWindow", "< X2 <"))
        self.x2_high_line.setText(_translate("MainWindow", "20"))
        self.x2clr_button.setText(_translate("MainWindow", "清除数据"))
        self.x2save_button.setText(_translate("MainWindow", "另存为"))
        self.x3_checkBox.setText(_translate("MainWindow", "范围："))
        self.x3_low_line.setText(_translate("MainWindow", "20"))
        self.label_14.setText(_translate("MainWindow", "< X3 <"))
        self.x3_high_line.setText(_translate("MainWindow", "100"))
        self.x3clr_button.setText(_translate("MainWindow", "清除数据"))
        self.x3save_button.setText(_translate("MainWindow", "另存为"))
        self.hexselec_radio.setText(_translate("MainWindow", "Hex 图形显示"))
        self.x1selec_radio.setText(_translate("MainWindow", "X1图形显示"))
        self.x2selec_radio.setText(_translate("MainWindow", "X2图形显示"))
        self.x3selec_radio.setText(_translate("MainWindow", "X3图形显示"))
        self.plotnum_lineEdit.setInputMask(_translate("MainWindow", "9999; "))
        self.plotnum_lineEdit.setText(_translate("MainWindow", "500"))
        self.debugtab.setTabText(self.debugtab.indexOf(self.debugdatatab), _translate("MainWindow", "DebugData"))
        self.debugtab.setTabText(self.debugtab.indexOf(self.matplottab), _translate("MainWindow", "Dataplot"))
        self.debugtab.setTabText(self.debugtab.indexOf(self.Instaspintab), _translate("MainWindow", "Instaspin "))
        self.maintabwidget.setTabText(self.maintabwidget.indexOf(self.scitooltab), _translate("MainWindow", "SciTool"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">串口调试工具</span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">TI Instaspin Foc</span><span style=\" font-size:10pt;\">交流群:</span><span style=\" font-size:10pt; text-decoration: underline;\">335663930</span><span style=\" font-size:10pt; font-weight:600;\"> Author</span><span style=\" font-size:10pt;\">@</span><span style=\" font-size:10pt; text-decoration: underline;\">nixianmin</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   <span style=\" font-size:12pt;\"> 最近在找一个能够利用串口来实现数据绘图的工具，用来做电机控制的调试，找了不少工具后发现没一个让我满意的，最后只能自己花点时间去写一个，花了不少时间，终于做了个差不多能用的</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">    这个工具除了实现简单的数据收发功能外，还能在DebugData界面将数据按照大小来区分出来，并且能够选择是否按照图形显示出来，对于用TI 的IQmath库的朋友，能够很容易利用库函数获得需要发送的数据格式。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">    另外我还做了一个功能就是能够实现单字节的数据图形显示，就是说利用一个字节即0~255，来代表一个数据的范围，快速刷新，能够达到1K以上的刷新速度。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">问题反馈：nixianmin@gmail.com</span></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.maintabwidget.setTabText(self.maintabwidget.indexOf(self.about_tab), _translate("MainWindow", "About"))
        self.label_11.setText(_translate("MainWindow", "接收数据："))
        self.recnumlineEdit.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "发送数据："))
        self.sendnum_lineEdit.setText(_translate("MainWindow", "0"))
        self.clrcntbutton.setText(_translate("MainWindow", "清计数"))

